#cloud-config
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtJlD26BHN7JbemjhfEL5BDSVTPkMBixqDxgsEli/hVpTPjhkZe+zxC4JRaPsVnKh857QIFjEAT/FZFeWZkj3mY/+mbhEVrSMSqefu73XN+Mk/DG08PNragp5dRnei+OYuCRTqkJCTa87bYl3WYSOfX2OzHByy2LZTUTCrzAbaZ5y7O/zYezBCIAv1OTy7ejdV8zvkBWblrootBous9/rZ+vRqkmDtLjxHphdiXm4xIchiHs4UvOhFDTd+XrmU3lYAR5L2BTyX8f5H63tESNX1GSRXmRd+pksoPQykEkOiAJ9tgKlmo6oEJxjvkD/Y6IotY31zkXOIApjnVL7zlOlr joseluiz
